#!/usr/bin/env bash
# Regenerate the TestDeployConfig CRD from the real one so the `test-crd`
# feature always sees the production schema. Run after every change to
# kubernetes/deploy-config-crd.yaml, then `kubectl apply -f` the result.
set -euo pipefail
cd "$(dirname "$0")/../.."
python3 - <<'PY'
import re
src = open('kubernetes/deploy-config-crd.yaml').read()
out = re.sub(r'\b(deployconfigs?|DeployConfig)\b',
             lambda m: ('Test' if m.group(1)[0] == 'D' else 'test') + m.group(1), src)
out = re.sub(r'(shortNames:\s*\n\s*- )dc\b', r'\1tdc', out)
header = '''# CRD for the `test-crd` cargo feature: identical schema to deploy-config-crd.yaml
# under kind TestDeployConfig, so a dev controller can run beside production.
# Generated by kubernetes/test-crd/regenerate.sh; do not edit by hand.
'''
open('kubernetes/test-crd/test-deploy-config-crd.yaml', 'w').write(header + out)
PY
echo "regenerated kubernetes/test-crd/test-deploy-config-crd.yaml"
