apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: backup-job
  namespace: default
spec:
  repo:
    owner: coolkev
    repo: backup-scripts
    default_branch: main
  autodeploy: true
  resourceType: CronJob
  spec:
    schedule: "0 2 * * *"  # Run at 2 AM every day
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: backup
              image: coolkev/backup-scripts:latest
              command: ["/bin/sh", "-c"]
              args:
              - |
                echo "Starting backup..."
                # Your backup script commands here
                echo "Backup completed"
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"
            restartPolicy: OnFailure
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
