apiVersion: cicd.coolkev.com/v1
kind: TestDeployConfig
metadata:
  name: test-alpha
  namespace: test
spec:
  autodeploy: false
  team: kj800x
  metadata:
  repo:
    owner: kj800x
    repo: test-repo
    defaultBranch: master
  specs:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-repo
        namespace: test
        labels:
          app: test-repo
      spec:
        replicas: 1
        revisionHistoryLimit: 1
        selector:
          matchLabels:
            app: test-repo
        template:
          metadata:
            labels:
              app: test-repo
          spec:
            imagePullSecrets:
              - name: ghcr-kj800x
            containers:
              - name: test-repo
                image: ghcr.io/kj800x/test-repo:commit-$SHA
                command: ["test-repo"]
                ports:
                  - containerPort: 8080
                    protocol: TCP
