apiVersion: cicd.coolkev.com/v1
kind: DeployConfig
metadata:
  name: backup-job
  namespace: default
spec:
  repo:
    owner: kj800x
    repo: test-repo
    defaultBranch: job-test
  autodeploy: true
  resourceType: CronJob
  spec:
    schedule: "0 2 * * *"  # Run at 2 AM every day
    jobTemplate:
      spec:
        template:
          spec:
            restartPolicy: OnFailure
            imagePullSecrets:
              - name: ghcr-kj800x
            containers:
              - name: test-job
                image: ghcr.io/kj800x/test-repo
                command: ["test-repo"]
